# Generated by Django 2.0 on 2022-12-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_census_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='census',
            unique_together={('voting_id', 'voter_id', 'type')},
        ),
    ]
