# Generated by Django 2.0 on 2022-11-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('O', 'Options'), ('B', 'Binary')], default='O', max_length=1),
        ),
    ]
